# Generated by Django 5.0.1 on 2024-01-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('account_number', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, default=50000, max_digits=19)),
                ('account_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.owner')),
            ],
        ),
    ]
