# Generated by Django 5.0.1 on 2024-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_owner_user_alter_owner_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
