# Generated by Django 5.0.1 on 2024-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bankuser_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=999999999999999),
        ),
    ]
