# Generated by Django 5.0.1 on 2024-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bankuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
