# Generated by Django 5.0.1 on 2024-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_bankuser_pfp_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='last_transfer',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
