# Generated by Django 5.0.1 on 2024-01-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_recipient_last_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankuser',
            name='pfp',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bankuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.bankuser')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.recipient')),
            ],
        ),
    ]
