# Generated by Django 5.0.1 on 2024-01-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_bankuser_pfp_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bankuser',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bankuser',
            field=models.ManyToManyField(to='base.bankuser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ManyToManyField(to='base.recipient'),
        ),
    ]
