# Generated by Django 5.0.1 on 2024-01-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_transaction_bankuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bankuser',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bankuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.bankuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.recipient'),
            preserve_default=False,
        ),
    ]
