# Generated by Django 5.0.1 on 2024-01-27 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_transaction_bankuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time_of_transfer',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
