# Generated by Django 5.0.1 on 2024-01-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_transaction_time_of_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='transfer_pin',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
