# Generated by Django 5.0.1 on 2024-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_bankuser_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
    ]
