# Generated by Django 5.0.1 on 2024-01-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='balance',
            field=models.IntegerField(default=500000),
        ),
    ]
