# Generated by Django 5.0.1 on 2024-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_bankuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
