# Generated by Django 4.2.10 on 2024-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_bankuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='money_in',
            field=models.BigIntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankuser',
            name='money_out',
            field=models.BigIntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='balance',
            field=models.IntegerField(default=9000000),
        ),
    ]
