# Generated by Django 4.2.10 on 2024-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_bankuser_money_in_bankuser_money_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='money_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='money_out',
            field=models.BigIntegerField(default=0),
        ),
    ]
