# Generated by Django 4.2.10 on 2024-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_bankuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
